### ISSUE TITLE
[BUG] CTD on start of emulation session in Direct3d graphics mode

### ISSUE THREAD

**Issue by carfesh** [petschau/WinFellow#105]
**Describe the bug**
WinFellow 0.5.10 will crash in Direct3d graphics mode when starting an emulation session. This was observed on a system with Amiga Forever 10 and an Intel UHD graphics chipset; issue was reported by Mike.

**To Reproduce**
The exact circumstances will need to be investigated.

**Expected behavior**
Instead of crashing WinFellow should fall back to DirectDraw mode if Direct3d cannot be used.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2

**WinFellow configuration**
see zip

**WinFellow logfile**
see zip

**Additional context**
[20231022-winfellow-0-5-10-1228-64-bit-d3d-11-MiniDump.zip](https://github.com/petschau/WinFellow/files/13062456/20231022-winfellow-0-5-10-1228-64-bit-d3d-11-MiniDump.zip)

**Comment by petschau** [comment]
Unfortunately cannot recreate. Log say D3D11CreateDevice() returns E_OUTOFMEMORY in this case. There are only a few mentions online of similar problems, some also then mention broken installed drivers, but nothing fits perfectly that I could find. 

For the moment, added validation of D3D11 device creation to the dxgi environment checks in case this can be discovered when starting the application. Also added more checks on error codes during session startup. Session startup will still fail if it goes that far, although controlled. It is not an easy place to rewind and do something else.

**Comment by carfesh** [comment]
I also could not reproduce this, even on a similar system that also has an Intel UHD chipset that I enforced to be used.. 

I could only test this by setting the result of the call to DeviceCreate to -1 instead of actually calling the function. In that test the fallback did allow the emulation session to start,  though. The Direct3d driver was removed from the selection in the dropdown list shown in the graphics options and the session started, also when I opened an emulation session with Amiga Forever configured to use Direct3d.

So I'm a little unclear if there still are any issues, we might create another test build?

**Comment by petschau** [comment]
I'll add the current changes to master. 

Still I find it hard to identify what problem we should be fixing here, and whether this is a very special case or not. 
One thing is check and fallback to directdraw, these changes do that based on the logged direct3d creation problem. 

But should Direct3d 11 have worked on this PC or is there simply a problem with the graphics driver that particular computer?  It is the first call to create the initial direct3d object that fails so it is not like we get to the point where we do anything with direct3d and we have so far no other examples of that happening.
