### ISSUE TITLE
Reformat files according to clang-format definition file

### ISSUE THREAD

**Issue by petschau** [petschau/WinFellow#114]
Since checking in changed files with the clang-format active will produce large diffs that obscure actual changes, we should make a one-time initial check-in to reformat the code-base according to the clang-format file.

**Comment by carfesh** [comment]
We might also want to configure further filters about which filetypes to use clang-format for; I've read in the "Format document on save" extension description that a .formatconfig file can be used for that: https://github.com/Elders/VSE-FormatDocumentOnSave

Not found anything useful yet about an easy way to save all files with that extension besides actually opening, editing and changing the files.

**Comment by carfesh** [comment]
I used the WSL command

find . -regex '.*\.\(c\|cpp\|hpp\|cc\|cxx\|h\)' -exec clang-format -style=file -i {} \;

in the solution directory to reformat the whole project using the file, the result is in the branch test-clang-format, where we should review if it looks like expected. I'm not sure if I hit all file extensions we need, I hope that I did.

**Comment by petschau** [comment]
There are some source files with upper-case extensions that the option -iregex will find.  In my opinion it is fine to format everything for simplicity. It might be possible to add exceptions, or additional clang-format files in directories, but not sure if I see the point.
