### ISSUE TITLE
IPF CAPS images

### ISSUE THREAD

**Issue by bumbaras** [petschau/WinFellow#17]
Version 0.5.4. Doesn't fully support ipf images.
- Lotus Challenge 2 - never stopped loading, never went to demo screen.
- Robocop - Guru Meditation after 2 seconds of loading (default settings for A500). When bogo mem is set to 512k there is no Guru Meditation screen, just auto restarts.
- Magic Pockets - OK, went to demo screen, didn't check further.
- Flashback - start animation and demo screen OK, didn't check any further.

**Comment by petschau** [comment]
Thanks for your feedback!  There was a bug stopping Lotus challenge 2 and Robocop from loading. Fixed in 8c240b5

**Comment by bumbaras** [comment]
You Guys are great. I didn't check the fix yet but I was pretty sure You will ignore my report due to few reasons - i didn't give You a md5 (or other crc sum) of IPF images (they could be damaged) and "what the hell this guy want from us" reason. But You still checked the report and fixed the bug. Great work.

**Comment by carfesh** [comment]
We just published a release to GitHub that includes this fix. If you want you can give it a shot, the version number is WinFellow v0.5.6.
