### ISSUE TITLE
Function blitterFillTableInit()

### ISSUE THREAD

**Issue by dirkwhoffmann** [petschau/WinFellow#29]
Just a tiny thing in function `static void blitterFillTableInit(void)`: 

    for (bit = 0; bit < 16; bit++)
    {
        if (mode == 0) data |= fc_tmp<<bit;
        else data ^= fc_tmp<<bit;
        if ((i & (0x1<<bit))) fc_tmp = (fc_tmp == 1) ? 0 : 1;
    }

It should be enough to iterate `bit`from 0 to <8. It's not really a bug, because the final table will be the same and runtime doesn't matter here.

BTW, is there a reason why you don't simply write `fc_tmp = !fc_tmp`?

**Comment by petschau** [comment]
Thanks, well observed! You're right, 8 is enough, I think this used to be a 16-bit table at some point. And in this case !fc_tmp will work the same. The only reason I can think of is that it is not used as a logical flag, it is an int that is being shifted.
