### ISSUE TITLE
enhancement: make pausing of emulation when window loses focus configurable

### ISSUE THREAD

**Issue by carfesh** [petschau/WinFellow#57]
Comments by jbl007 in the EAB forum (http://eab.abime.net/showpost.php?p=1329704&postcount=2)

> Why does the emulation pause when the window lost focus? Is this a bug or a feature? 

 [...]

> Ah, ok. I didn't know. I haven't used it since ages. 
> Not very multitasking friendly if you ask me, hehe. Are there plans to change this/make it configurable? There's plenty of space in the "various" tab. 

Should we possibly make this configurable in version 0.5.9?

**Comment by carfesh** [comment]
GfxDrvCommon.cpp, GfxDrvCommon::EvaluateRunEventStatus() - resetting of the runevent would need to be disabled for emulation to continue running in the background?

**Comment by carfesh** [comment]
I would imagine that this might work best as a clickable menu option in a new "Options" menu, that is saved into the winfellow.ini (so not configuration specific, but as a global option)

**Comment by petschau** [comment]
EvaluateRunEventStatus() is the place to change this. This is already implemented for RP mode, isn't it? We also need to investigate if fullscreen-modes still need this.

**Comment by carfesh** [comment]
It is, yes. In a quick test I couldn't find any problems when I created the option. I committed a version to a tryout branch, will have to test some more with it, but a first test looked good to me, also when using fullscreen. I can see situations where it would be nice to have this configurable, like when wanting to play retro music in the background, with the emulation being minimized.

**Comment by petschau** [comment]
It behaved well when I tested it on Windows 10.

**Comment by carfesh** [comment]
Good to hear! It is still a tryout branch, IMO it is not ready to be merged yet. I will look at making the menu code a bit more reusable. I had just put everything in place that was needed for a quick prototype, but I feel I'd like to change a thing here or there before we merge it. I'll also have to do some integration testing with Amiga Forever, as well as DirectDraw vs. Direct3D fullscreen modes.
