### ISSUE TITLE
[BUG] error during wb installation to filesystem

### ISSUE THREAD

**Issue by carfesh** [petschau/WinFellow#65]
**Describe the bug**
Installation of WB 3.1 will fail on my notebook while copying the file "AUX". On my main PC, this had worked fine.

**To Reproduce**
1. Create a config based on A3000 profile
2. Configure a filesystem C:\fswb, enable autoconfig devices
3. insert 4 WB floppies
4. attempt installation with german keyboard

**Expected behavior**
Installation should finish without errors.

**Screenshots**
![2019-07-02 06_19_34-2019-07-01 18_09_13- png - Greenshot Editor](https://user-images.githubusercontent.com/16491101/60482348-60383c80-9c91-11e9-924d-f95f7532c0a5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**WinFellow logfile**
[fellow.log](https://github.com/petschau/WinFellow/files/3348398/fellow.log)

**Additional context**
Happens in WinFellow 0.5.7, 0.5.8 RC-1 as well as 0.5.9-dev, so it does not seem to be a regression. No time now, will need to examine this further, there is special handling in place for files named AUX, maybe something else influences the error occuring. The log even says "unique name:" at that point, something surrounding this seems to be going wrong.

**Comment by carfesh** [comment]
An easy way to reproduce not the same, but a similar issue that is easier to test for is to use the Workbench menus to create a new empty folder called AUX. On my laptop it will frequently fail to rename Unnamed1.info to AUX.info using C rename(), probably because some handles to the file are still open (AV?).

In UAE, the filesystem code has been updated significantly compared to the version we have integrated, so while the filesystem code hasn't had issues for a long while, an update may make sense to keep them in sync and compatible.

Updating to a new version would however be severe effort, as the code has been changed in many, many places. UAE code has also been adjusted to use generic string representations (TCHAR, _tcs functions, etc.)

In UAE, the code has been adjusted for Windows peculiarities in fsdb_mywin32.cpp, and re-using my_rename() worked fine for that particular case. 

We might try to re-use those functions in the places where this is an issue as a short-term solution. 

Still, we should maybe take a moment to evaluate how the code can be wrapped in a way that allows easier updates in the future.

**Comment by petschau** [comment]
It might make sense to re-use functions rather than take in the whole code, there are a lot of changes compared to what we originally imported from the UAE source. I am also wondering to what degree the underlying "plumbing" of the filesystem has technical or functional changes, too. And at first glance the filesystem bootrom seems to have become very entangled with other non-fs functionality, not to mention the filesystem code itself appears to have content related to RDB, IDE, SCSI and mousehacks etc.

**Comment by carfesh** [comment]
Right now I can no longer reproduce this issue.
