### ISSUE TITLE
[BUG] error using presets with encrypted ROMs

### ISSUE THREAD

**Issue by carfesh** [petschau/WinFellow#67]
**Describe the bug**
Hi there, was just playing around with Winfellow and when I selected amiga 500 in the presets, it keeps popping this error window. It won't let me close it by clicking on OK. I have to end-task it to get back in. I know I have to pre-select the kickstart but it should not prevent me from closing it and go back. Just FYI.

**Screenshots**
![Annotation 2019-07-29 193703](https://user-images.githubusercontent.com/16491101/62188935-11ec8b00-b36e-11e9-9d2d-1ed5d7f3987f.png)

**Source**
Bug report from EAB: http://eab.abime.net/showpost.php?p=1335370&postcount=7

**Comment by sama11y** [comment]
551edc560ba93c59d5e29e34889eed52578fe795
